#
# Prezto runcoms - Default configuration
#

#
# Sets directory options.
#
setopt AUTO_CD              # Auto changes to a directory without typing cd.
setopt AUTO_PUSHD           # Push the old directory onto the stack on cd.
setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.
setopt PUSHD_TO_HOME        # Have pushd with no arguments act like 'pushd ${HOME}'.
setopt RM_STAR_WAIT        # Do not ask for confirmation before executing 'rm *' or 'rm path/*'.
setopt EXTENDED_GLOB        # Use extended globbing syntax.
setopt CLOBBER             # Allow > redirection to truncate existing files. >! to force.

#
# Environment
#
export LANG='en_US.UTF-8'
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Aliases
#
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

#
# Key bindings
#
bindkey -v  # Use vi key bindings
